version: '3'


services:
  complement2:
    build: ./complement2
  nginx:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - complement2