version: '3'

services:
  sistemas:
    build: ./services/sistemas
  ti:
    build: ./services/ti
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
    ports:
      - "3000:3000"
  mongo:
    image: mongo
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sistemas
      - ti

















  
